// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotorType.proto

package org.jam.protobuf.dynamic;

public final class MotorTypeOuterClass {
  private MotorTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MotorTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MotorType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string object_id = 1;</code>
     * @return The objectId.
     */
    java.lang.String getObjectId();
    /**
     * <code>string object_id = 1;</code>
     * @return The bytes for objectId.
     */
    com.google.protobuf.ByteString
        getObjectIdBytes();

    /**
     * <code>string object_type = 2;</code>
     * @return The objectType.
     */
    java.lang.String getObjectType();
    /**
     * <code>string object_type = 2;</code>
     * @return The bytes for objectType.
     */
    com.google.protobuf.ByteString
        getObjectTypeBytes();

    /**
     * <code>repeated .MotorType.Measurement measurements = 3;</code>
     */
    java.util.List<MotorTypeOuterClass.MotorType.Measurement> 
        getMeasurementsList();
    /**
     * <code>repeated .MotorType.Measurement measurements = 3;</code>
     */
    MotorTypeOuterClass.MotorType.Measurement getMeasurements(int index);
    /**
     * <code>repeated .MotorType.Measurement measurements = 3;</code>
     */
    int getMeasurementsCount();
    /**
     * <code>repeated .MotorType.Measurement measurements = 3;</code>
     */
    java.util.List<? extends MotorTypeOuterClass.MotorType.MeasurementOrBuilder> 
        getMeasurementsOrBuilderList();
    /**
     * <code>repeated .MotorType.Measurement measurements = 3;</code>
     */
    MotorTypeOuterClass.MotorType.MeasurementOrBuilder getMeasurementsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MotorType}
   */
  public static final class MotorType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MotorType)
      MotorTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MotorType.newBuilder() to construct.
    private MotorType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MotorType() {
      objectId_ = "";
      objectType_ = "";
      measurements_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MotorType();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MotorType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              objectId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              objectType_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                measurements_ = new java.util.ArrayList<MotorTypeOuterClass.MotorType.Measurement>();
                mutable_bitField0_ |= 0x00000001;
              }
              measurements_.add(
                  input.readMessage(MotorTypeOuterClass.MotorType.Measurement.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          measurements_ = java.util.Collections.unmodifiableList(measurements_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MotorTypeOuterClass.internal_static_MotorType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MotorTypeOuterClass.internal_static_MotorType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MotorTypeOuterClass.MotorType.class, MotorTypeOuterClass.MotorType.Builder.class);
    }

    public interface MeasurementOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MotorType.Measurement)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 _time = 1;</code>
       * @return The time.
       */
      long getTime();

      /**
       * <code>string _path = 2;</code>
       * @return The path.
       */
      java.lang.String getPath();
      /**
       * <code>string _path = 2;</code>
       * @return The bytes for path.
       */
      com.google.protobuf.ByteString
          getPathBytes();

      /**
       * <code>double GearRatio = 3;</code>
       * @return The gearRatio.
       */
      double getGearRatio();

      /**
       * <code>double Pitch = 4;</code>
       * @return The pitch.
       */
      double getPitch();
    }
    /**
     * Protobuf type {@code MotorType.Measurement}
     */
    public static final class Measurement extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:MotorType.Measurement)
        MeasurementOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Measurement.newBuilder() to construct.
      private Measurement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Measurement() {
        Path_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Measurement();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Measurement(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                Time_ = input.readInt64();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                Path_ = s;
                break;
              }
              case 25: {

                gearRatio_ = input.readDouble();
                break;
              }
              case 33: {

                pitch_ = input.readDouble();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MotorTypeOuterClass.internal_static_MotorType_Measurement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MotorTypeOuterClass.internal_static_MotorType_Measurement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MotorTypeOuterClass.MotorType.Measurement.class, MotorTypeOuterClass.MotorType.Measurement.Builder.class);
      }

      public static final int _TIME_FIELD_NUMBER = 1;
      private long Time_;
      /**
       * <code>int64 _time = 1;</code>
       * @return The time.
       */
      @java.lang.Override
      public long getTime() {
        return Time_;
      }

      public static final int _PATH_FIELD_NUMBER = 2;
      private volatile java.lang.Object Path_;
      /**
       * <code>string _path = 2;</code>
       * @return The path.
       */
      @java.lang.Override
      public java.lang.String getPath() {
        java.lang.Object ref = Path_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          Path_ = s;
          return s;
        }
      }
      /**
       * <code>string _path = 2;</code>
       * @return The bytes for path.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = Path_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          Path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int GEARRATIO_FIELD_NUMBER = 3;
      private double gearRatio_;
      /**
       * <code>double GearRatio = 3;</code>
       * @return The gearRatio.
       */
      @java.lang.Override
      public double getGearRatio() {
        return gearRatio_;
      }

      public static final int PITCH_FIELD_NUMBER = 4;
      private double pitch_;
      /**
       * <code>double Pitch = 4;</code>
       * @return The pitch.
       */
      @java.lang.Override
      public double getPitch() {
        return pitch_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (Time_ != 0L) {
          output.writeInt64(1, Time_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(Path_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, Path_);
        }
        if (java.lang.Double.doubleToRawLongBits(gearRatio_) != 0) {
          output.writeDouble(3, gearRatio_);
        }
        if (java.lang.Double.doubleToRawLongBits(pitch_) != 0) {
          output.writeDouble(4, pitch_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (Time_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, Time_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(Path_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, Path_);
        }
        if (java.lang.Double.doubleToRawLongBits(gearRatio_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, gearRatio_);
        }
        if (java.lang.Double.doubleToRawLongBits(pitch_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, pitch_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof MotorTypeOuterClass.MotorType.Measurement)) {
          return super.equals(obj);
        }
        MotorTypeOuterClass.MotorType.Measurement other = (MotorTypeOuterClass.MotorType.Measurement) obj;

        if (getTime()
            != other.getTime()) return false;
        if (!getPath()
            .equals(other.getPath())) return false;
        if (java.lang.Double.doubleToLongBits(getGearRatio())
            != java.lang.Double.doubleToLongBits(
                other.getGearRatio())) return false;
        if (java.lang.Double.doubleToLongBits(getPitch())
            != java.lang.Double.doubleToLongBits(
                other.getPitch())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + _TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
        hash = (37 * hash) + _PATH_FIELD_NUMBER;
        hash = (53 * hash) + getPath().hashCode();
        hash = (37 * hash) + GEARRATIO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getGearRatio()));
        hash = (37 * hash) + PITCH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPitch()));
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static MotorTypeOuterClass.MotorType.Measurement parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MotorTypeOuterClass.MotorType.Measurement parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(MotorTypeOuterClass.MotorType.Measurement prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code MotorType.Measurement}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:MotorType.Measurement)
          MotorTypeOuterClass.MotorType.MeasurementOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return MotorTypeOuterClass.internal_static_MotorType_Measurement_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return MotorTypeOuterClass.internal_static_MotorType_Measurement_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  MotorTypeOuterClass.MotorType.Measurement.class, MotorTypeOuterClass.MotorType.Measurement.Builder.class);
        }

        // Construct using MotorTypeOuterClass.MotorType.Measurement.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          Time_ = 0L;

          Path_ = "";

          gearRatio_ = 0D;

          pitch_ = 0D;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return MotorTypeOuterClass.internal_static_MotorType_Measurement_descriptor;
        }

        @java.lang.Override
        public MotorTypeOuterClass.MotorType.Measurement getDefaultInstanceForType() {
          return MotorTypeOuterClass.MotorType.Measurement.getDefaultInstance();
        }

        @java.lang.Override
        public MotorTypeOuterClass.MotorType.Measurement build() {
          MotorTypeOuterClass.MotorType.Measurement result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public MotorTypeOuterClass.MotorType.Measurement buildPartial() {
          MotorTypeOuterClass.MotorType.Measurement result = new MotorTypeOuterClass.MotorType.Measurement(this);
          result.Time_ = Time_;
          result.Path_ = Path_;
          result.gearRatio_ = gearRatio_;
          result.pitch_ = pitch_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof MotorTypeOuterClass.MotorType.Measurement) {
            return mergeFrom((MotorTypeOuterClass.MotorType.Measurement)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(MotorTypeOuterClass.MotorType.Measurement other) {
          if (other == MotorTypeOuterClass.MotorType.Measurement.getDefaultInstance()) return this;
          if (other.getTime() != 0L) {
            setTime(other.getTime());
          }
          if (!other.getPath().isEmpty()) {
            Path_ = other.Path_;
            onChanged();
          }
          if (other.getGearRatio() != 0D) {
            setGearRatio(other.getGearRatio());
          }
          if (other.getPitch() != 0D) {
            setPitch(other.getPitch());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          MotorTypeOuterClass.MotorType.Measurement parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (MotorTypeOuterClass.MotorType.Measurement) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long Time_ ;
        /**
         * <code>int64 _time = 1;</code>
         * @return The time.
         */
        @java.lang.Override
        public long getTime() {
          return Time_;
        }
        /**
         * <code>int64 _time = 1;</code>
         * @param value The time to set.
         * @return This builder for chaining.
         */
        public Builder setTime(long value) {
          
          Time_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 _time = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearTime() {
          
          Time_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object Path_ = "";
        /**
         * <code>string _path = 2;</code>
         * @return The path.
         */
        public java.lang.String getPath() {
          java.lang.Object ref = Path_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            Path_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string _path = 2;</code>
         * @return The bytes for path.
         */
        public com.google.protobuf.ByteString
            getPathBytes() {
          java.lang.Object ref = Path_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            Path_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string _path = 2;</code>
         * @param value The path to set.
         * @return This builder for chaining.
         */
        public Builder setPath(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          Path_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string _path = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearPath() {
          
          Path_ = getDefaultInstance().getPath();
          onChanged();
          return this;
        }
        /**
         * <code>string _path = 2;</code>
         * @param value The bytes for path to set.
         * @return This builder for chaining.
         */
        public Builder setPathBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          Path_ = value;
          onChanged();
          return this;
        }

        private double gearRatio_ ;
        /**
         * <code>double GearRatio = 3;</code>
         * @return The gearRatio.
         */
        @java.lang.Override
        public double getGearRatio() {
          return gearRatio_;
        }
        /**
         * <code>double GearRatio = 3;</code>
         * @param value The gearRatio to set.
         * @return This builder for chaining.
         */
        public Builder setGearRatio(double value) {
          
          gearRatio_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double GearRatio = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearGearRatio() {
          
          gearRatio_ = 0D;
          onChanged();
          return this;
        }

        private double pitch_ ;
        /**
         * <code>double Pitch = 4;</code>
         * @return The pitch.
         */
        @java.lang.Override
        public double getPitch() {
          return pitch_;
        }
        /**
         * <code>double Pitch = 4;</code>
         * @param value The pitch to set.
         * @return This builder for chaining.
         */
        public Builder setPitch(double value) {
          
          pitch_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double Pitch = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearPitch() {
          
          pitch_ = 0D;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:MotorType.Measurement)
      }

      // @@protoc_insertion_point(class_scope:MotorType.Measurement)
      private static final MotorTypeOuterClass.MotorType.Measurement DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new MotorTypeOuterClass.MotorType.Measurement();
      }

      public static MotorTypeOuterClass.MotorType.Measurement getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Measurement>
          PARSER = new com.google.protobuf.AbstractParser<Measurement>() {
        @java.lang.Override
        public Measurement parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Measurement(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Measurement> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Measurement> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public MotorTypeOuterClass.MotorType.Measurement getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int OBJECT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object objectId_;
    /**
     * <code>string object_id = 1;</code>
     * @return The objectId.
     */
    @java.lang.Override
    public java.lang.String getObjectId() {
      java.lang.Object ref = objectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectId_ = s;
        return s;
      }
    }
    /**
     * <code>string object_id = 1;</code>
     * @return The bytes for objectId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getObjectIdBytes() {
      java.lang.Object ref = objectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OBJECT_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object objectType_;
    /**
     * <code>string object_type = 2;</code>
     * @return The objectType.
     */
    @java.lang.Override
    public java.lang.String getObjectType() {
      java.lang.Object ref = objectType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectType_ = s;
        return s;
      }
    }
    /**
     * <code>string object_type = 2;</code>
     * @return The bytes for objectType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getObjectTypeBytes() {
      java.lang.Object ref = objectType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEASUREMENTS_FIELD_NUMBER = 3;
    private java.util.List<MotorTypeOuterClass.MotorType.Measurement> measurements_;
    /**
     * <code>repeated .MotorType.Measurement measurements = 3;</code>
     */
    @java.lang.Override
    public java.util.List<MotorTypeOuterClass.MotorType.Measurement> getMeasurementsList() {
      return measurements_;
    }
    /**
     * <code>repeated .MotorType.Measurement measurements = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends MotorTypeOuterClass.MotorType.MeasurementOrBuilder> 
        getMeasurementsOrBuilderList() {
      return measurements_;
    }
    /**
     * <code>repeated .MotorType.Measurement measurements = 3;</code>
     */
    @java.lang.Override
    public int getMeasurementsCount() {
      return measurements_.size();
    }
    /**
     * <code>repeated .MotorType.Measurement measurements = 3;</code>
     */
    @java.lang.Override
    public MotorTypeOuterClass.MotorType.Measurement getMeasurements(int index) {
      return measurements_.get(index);
    }
    /**
     * <code>repeated .MotorType.Measurement measurements = 3;</code>
     */
    @java.lang.Override
    public MotorTypeOuterClass.MotorType.MeasurementOrBuilder getMeasurementsOrBuilder(
        int index) {
      return measurements_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, objectType_);
      }
      for (int i = 0; i < measurements_.size(); i++) {
        output.writeMessage(3, measurements_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, objectType_);
      }
      for (int i = 0; i < measurements_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, measurements_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MotorTypeOuterClass.MotorType)) {
        return super.equals(obj);
      }
      MotorTypeOuterClass.MotorType other = (MotorTypeOuterClass.MotorType) obj;

      if (!getObjectId()
          .equals(other.getObjectId())) return false;
      if (!getObjectType()
          .equals(other.getObjectType())) return false;
      if (!getMeasurementsList()
          .equals(other.getMeasurementsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OBJECT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getObjectId().hashCode();
      hash = (37 * hash) + OBJECT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getObjectType().hashCode();
      if (getMeasurementsCount() > 0) {
        hash = (37 * hash) + MEASUREMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getMeasurementsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MotorTypeOuterClass.MotorType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MotorTypeOuterClass.MotorType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MotorTypeOuterClass.MotorType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MotorTypeOuterClass.MotorType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MotorTypeOuterClass.MotorType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MotorTypeOuterClass.MotorType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MotorTypeOuterClass.MotorType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MotorTypeOuterClass.MotorType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MotorTypeOuterClass.MotorType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MotorTypeOuterClass.MotorType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MotorTypeOuterClass.MotorType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MotorTypeOuterClass.MotorType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MotorTypeOuterClass.MotorType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MotorType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MotorType)
        MotorTypeOuterClass.MotorTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MotorTypeOuterClass.internal_static_MotorType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MotorTypeOuterClass.internal_static_MotorType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MotorTypeOuterClass.MotorType.class, MotorTypeOuterClass.MotorType.Builder.class);
      }

      // Construct using MotorTypeOuterClass.MotorType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMeasurementsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        objectId_ = "";

        objectType_ = "";

        if (measurementsBuilder_ == null) {
          measurements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          measurementsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MotorTypeOuterClass.internal_static_MotorType_descriptor;
      }

      @java.lang.Override
      public MotorTypeOuterClass.MotorType getDefaultInstanceForType() {
        return MotorTypeOuterClass.MotorType.getDefaultInstance();
      }

      @java.lang.Override
      public MotorTypeOuterClass.MotorType build() {
        MotorTypeOuterClass.MotorType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MotorTypeOuterClass.MotorType buildPartial() {
        MotorTypeOuterClass.MotorType result = new MotorTypeOuterClass.MotorType(this);
        int from_bitField0_ = bitField0_;
        result.objectId_ = objectId_;
        result.objectType_ = objectType_;
        if (measurementsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            measurements_ = java.util.Collections.unmodifiableList(measurements_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.measurements_ = measurements_;
        } else {
          result.measurements_ = measurementsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MotorTypeOuterClass.MotorType) {
          return mergeFrom((MotorTypeOuterClass.MotorType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MotorTypeOuterClass.MotorType other) {
        if (other == MotorTypeOuterClass.MotorType.getDefaultInstance()) return this;
        if (!other.getObjectId().isEmpty()) {
          objectId_ = other.objectId_;
          onChanged();
        }
        if (!other.getObjectType().isEmpty()) {
          objectType_ = other.objectType_;
          onChanged();
        }
        if (measurementsBuilder_ == null) {
          if (!other.measurements_.isEmpty()) {
            if (measurements_.isEmpty()) {
              measurements_ = other.measurements_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMeasurementsIsMutable();
              measurements_.addAll(other.measurements_);
            }
            onChanged();
          }
        } else {
          if (!other.measurements_.isEmpty()) {
            if (measurementsBuilder_.isEmpty()) {
              measurementsBuilder_.dispose();
              measurementsBuilder_ = null;
              measurements_ = other.measurements_;
              bitField0_ = (bitField0_ & ~0x00000001);
              measurementsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMeasurementsFieldBuilder() : null;
            } else {
              measurementsBuilder_.addAllMessages(other.measurements_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MotorTypeOuterClass.MotorType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MotorTypeOuterClass.MotorType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object objectId_ = "";
      /**
       * <code>string object_id = 1;</code>
       * @return The objectId.
       */
      public java.lang.String getObjectId() {
        java.lang.Object ref = objectId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          objectId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string object_id = 1;</code>
       * @return The bytes for objectId.
       */
      public com.google.protobuf.ByteString
          getObjectIdBytes() {
        java.lang.Object ref = objectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string object_id = 1;</code>
       * @param value The objectId to set.
       * @return This builder for chaining.
       */
      public Builder setObjectId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        objectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string object_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearObjectId() {
        
        objectId_ = getDefaultInstance().getObjectId();
        onChanged();
        return this;
      }
      /**
       * <code>string object_id = 1;</code>
       * @param value The bytes for objectId to set.
       * @return This builder for chaining.
       */
      public Builder setObjectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        objectId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object objectType_ = "";
      /**
       * <code>string object_type = 2;</code>
       * @return The objectType.
       */
      public java.lang.String getObjectType() {
        java.lang.Object ref = objectType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          objectType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string object_type = 2;</code>
       * @return The bytes for objectType.
       */
      public com.google.protobuf.ByteString
          getObjectTypeBytes() {
        java.lang.Object ref = objectType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string object_type = 2;</code>
       * @param value The objectType to set.
       * @return This builder for chaining.
       */
      public Builder setObjectType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        objectType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string object_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearObjectType() {
        
        objectType_ = getDefaultInstance().getObjectType();
        onChanged();
        return this;
      }
      /**
       * <code>string object_type = 2;</code>
       * @param value The bytes for objectType to set.
       * @return This builder for chaining.
       */
      public Builder setObjectTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        objectType_ = value;
        onChanged();
        return this;
      }

      private java.util.List<MotorTypeOuterClass.MotorType.Measurement> measurements_ =
        java.util.Collections.emptyList();
      private void ensureMeasurementsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          measurements_ = new java.util.ArrayList<MotorTypeOuterClass.MotorType.Measurement>(measurements_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MotorTypeOuterClass.MotorType.Measurement, MotorTypeOuterClass.MotorType.Measurement.Builder, MotorTypeOuterClass.MotorType.MeasurementOrBuilder> measurementsBuilder_;

      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public java.util.List<MotorTypeOuterClass.MotorType.Measurement> getMeasurementsList() {
        if (measurementsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(measurements_);
        } else {
          return measurementsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public int getMeasurementsCount() {
        if (measurementsBuilder_ == null) {
          return measurements_.size();
        } else {
          return measurementsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public MotorTypeOuterClass.MotorType.Measurement getMeasurements(int index) {
        if (measurementsBuilder_ == null) {
          return measurements_.get(index);
        } else {
          return measurementsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public Builder setMeasurements(
          int index, MotorTypeOuterClass.MotorType.Measurement value) {
        if (measurementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasurementsIsMutable();
          measurements_.set(index, value);
          onChanged();
        } else {
          measurementsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public Builder setMeasurements(
          int index, MotorTypeOuterClass.MotorType.Measurement.Builder builderForValue) {
        if (measurementsBuilder_ == null) {
          ensureMeasurementsIsMutable();
          measurements_.set(index, builderForValue.build());
          onChanged();
        } else {
          measurementsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public Builder addMeasurements(MotorTypeOuterClass.MotorType.Measurement value) {
        if (measurementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasurementsIsMutable();
          measurements_.add(value);
          onChanged();
        } else {
          measurementsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public Builder addMeasurements(
          int index, MotorTypeOuterClass.MotorType.Measurement value) {
        if (measurementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasurementsIsMutable();
          measurements_.add(index, value);
          onChanged();
        } else {
          measurementsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public Builder addMeasurements(
          MotorTypeOuterClass.MotorType.Measurement.Builder builderForValue) {
        if (measurementsBuilder_ == null) {
          ensureMeasurementsIsMutable();
          measurements_.add(builderForValue.build());
          onChanged();
        } else {
          measurementsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public Builder addMeasurements(
          int index, MotorTypeOuterClass.MotorType.Measurement.Builder builderForValue) {
        if (measurementsBuilder_ == null) {
          ensureMeasurementsIsMutable();
          measurements_.add(index, builderForValue.build());
          onChanged();
        } else {
          measurementsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public Builder addAllMeasurements(
          java.lang.Iterable<? extends MotorTypeOuterClass.MotorType.Measurement> values) {
        if (measurementsBuilder_ == null) {
          ensureMeasurementsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, measurements_);
          onChanged();
        } else {
          measurementsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public Builder clearMeasurements() {
        if (measurementsBuilder_ == null) {
          measurements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          measurementsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public Builder removeMeasurements(int index) {
        if (measurementsBuilder_ == null) {
          ensureMeasurementsIsMutable();
          measurements_.remove(index);
          onChanged();
        } else {
          measurementsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public MotorTypeOuterClass.MotorType.Measurement.Builder getMeasurementsBuilder(
          int index) {
        return getMeasurementsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public MotorTypeOuterClass.MotorType.MeasurementOrBuilder getMeasurementsOrBuilder(
          int index) {
        if (measurementsBuilder_ == null) {
          return measurements_.get(index);  } else {
          return measurementsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public java.util.List<? extends MotorTypeOuterClass.MotorType.MeasurementOrBuilder> 
           getMeasurementsOrBuilderList() {
        if (measurementsBuilder_ != null) {
          return measurementsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(measurements_);
        }
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public MotorTypeOuterClass.MotorType.Measurement.Builder addMeasurementsBuilder() {
        return getMeasurementsFieldBuilder().addBuilder(
            MotorTypeOuterClass.MotorType.Measurement.getDefaultInstance());
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public MotorTypeOuterClass.MotorType.Measurement.Builder addMeasurementsBuilder(
          int index) {
        return getMeasurementsFieldBuilder().addBuilder(
            index, MotorTypeOuterClass.MotorType.Measurement.getDefaultInstance());
      }
      /**
       * <code>repeated .MotorType.Measurement measurements = 3;</code>
       */
      public java.util.List<MotorTypeOuterClass.MotorType.Measurement.Builder> 
           getMeasurementsBuilderList() {
        return getMeasurementsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MotorTypeOuterClass.MotorType.Measurement, MotorTypeOuterClass.MotorType.Measurement.Builder, MotorTypeOuterClass.MotorType.MeasurementOrBuilder> 
          getMeasurementsFieldBuilder() {
        if (measurementsBuilder_ == null) {
          measurementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MotorTypeOuterClass.MotorType.Measurement, MotorTypeOuterClass.MotorType.Measurement.Builder, MotorTypeOuterClass.MotorType.MeasurementOrBuilder>(
                  measurements_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          measurements_ = null;
        }
        return measurementsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MotorType)
    }

    // @@protoc_insertion_point(class_scope:MotorType)
    private static final MotorTypeOuterClass.MotorType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MotorTypeOuterClass.MotorType();
    }

    public static MotorTypeOuterClass.MotorType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MotorType>
        PARSER = new com.google.protobuf.AbstractParser<MotorType>() {
      @java.lang.Override
      public MotorType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MotorType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MotorType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MotorType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MotorTypeOuterClass.MotorType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MotorType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MotorType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MotorType_Measurement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MotorType_Measurement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MotorType.proto\"\260\001\n\tMotorType\022\021\n\tobjec" +
      "t_id\030\001 \001(\t\022\023\n\013object_type\030\002 \001(\t\022,\n\014measu" +
      "rements\030\003 \003(\0132\026.MotorType.Measurement\032M\n" +
      "\013Measurement\022\r\n\005_time\030\001 \001(\003\022\r\n\005_path\030\002 \001" +
      "(\t\022\021\n\tGearRatio\030\003 \001(\001\022\r\n\005Pitch\030\004 \001(\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MotorType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MotorType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MotorType_descriptor,
        new java.lang.String[] { "ObjectId", "ObjectType", "Measurements", });
    internal_static_MotorType_Measurement_descriptor =
      internal_static_MotorType_descriptor.getNestedTypes().get(0);
    internal_static_MotorType_Measurement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MotorType_Measurement_descriptor,
        new java.lang.String[] { "Time", "Path", "GearRatio", "Pitch", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
